### ISSUE TITLE
Not an Issue, just a question 

### ISSUE THREAD

**Issue by hvddrift** [Supergiovane/node-red-contrib-boolean-logic-ultimate#10]
Hi

Great project. 

How would I to make a NAND gate with your nodes please?

Thanks

**Comment by Supergiovane** [comment]
Hello,
Thanks. Will do. Stay tuned.

**Comment by Supergiovane** [comment]
PS: in the meantime, you cannput an invert node after an and node.

**Comment by Supergiovane** [comment]
Simply added an help on how to obtain NAND and NOR ports, in the README and in the contextual help. This to leave the node as simple as possible.
