### ISSUE TITLE
A simple deploy shouldn't delere persistent states

### ISSUE THREAD

**Issue by ChristianMayer** [Supergiovane/node-red-contrib-boolean-logic-ultimate#11]
As I'm currently creating many new flows I have to deploy regularly. But each deploy is deleting my persistent states, which doesn't make sense here.

Is it possible to prevent prevent that?

**Comment by Supergiovane** [comment]
Hi
The node’s goal is to mantain states. 
have you set the node, not to delete the cache folder? The option is in the config window.

**Comment by ChristianMayer** [comment]
Yes, this is the full config of one of the nodes where I can see deleting:
![Screenshot_20210110_144644](https://user-images.githubusercontent.com/10218721/104124758-c73cb400-5352-11eb-8ad9-20367ef7fcdf.png)

**Comment by Supergiovane** [comment]
Please be sure that the node-red user has permission to write to the filesystem.
The folder where the node stores the states, is this:
**.node-red/booleanlogicultimatepersist**
Can you check that, please?

**Comment by Supergiovane** [comment]
Please, unzip the content of the attachment into the
**.node-red/node_modules/node-red-contrib-boolean-logic-ultimate/boolean-logic-ultimate folder** and restart nodered.
This will output an error everytime the boolean logic node is unable to write to the filesystem.
Then, please paste here the error.
Thanks.

[BooleanLogicUltimate.js.zip](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/files/5792702/BooleanLogicUltimate.js.zip)

**Comment by Supergiovane** [comment]
Hey @ChristianMayer 
please let me know.
If you run nodered behind redmatic, homeassistant etc... you should assure the write access to the **.node-red** folder.

**Comment by ChristianMayer** [comment]
That directory seems to work fine, files are there, modification time looks good:
![Screenshot_20210110_213007](https://user-images.githubusercontent.com/10218721/104134614-143c7c80-538b-11eb-832b-fc121e269789.png)
I'm running the official Docker image `nodered/node-red:latest`

Should I still try the ZIP file?

**Comment by Supergiovane** [comment]
Hi Christian
Nope. If you can open one of these files and tell me the content, it will be helpful. 
Whenever you deploy, are these files wiped out?

**Comment by Supergiovane** [comment]
@ChristianMayer Hello Christian
have you solved the issue?

**Comment by Supergiovane** [comment]
@ChristianMayer Hi, the persistent states file is deleted only whenever you open the property window of boolean-logic-ultimate (and only the file belonging to that node). Otherwise they'll never been deleted.

**Comment by ChristianMayer** [comment]
Hi Giovane,

sorry for answering late but I was busy on the one hand and wanted to understand the behavior on the other.

Currently it's behaving correctly, i.e. it's solved. But the path to that is strange, so I'm not sure whether that is really solved:

I have detected that in a different flow I had a problem with the topics, so there was a boolean node, listening for two topics although it was fed with more than that due to a setup mistake from me. But that flow is independent from the flow that I was closely monitoring and that was the base for this issue report.
Once I resolved the mistake on the other flow (without touching anything on the monitored flow) the deletion of the persistent states went here away as well.
What's even more strange: adding a 2-topic bool with three inject nodes and thus creating such a mistake on purpose again doesn't trigger the observed behavior.

When this description gives you a hint of what to check that's great. If it doesn't I'm also fine with closing this topic in the hope that it's no issue anymore (and when it's coming back I'll report back)

**Comment by Supergiovane** [comment]
Hi Chris
That's very unusual, but i saw a think like that in another my node (KNX-Ultimate) of one user.
I struggled to try to help the user, until it sent me their flow.
The user had logged to node-red from 2 different browsers, making the bad decision to click "OK" in the "would you like to merge the changes?" popup window of one of the browsers.
The result? A mess in the json configuration. 
I had to manually change all node's IDs in the config file of that user.
Another time, i saw a strange things due to a "devil char" in the config Json.
You should be fine now. If not, please don't hesitate to contact me again.

Please bear in mind, that each time you enter the boolean logic's ultimate config window, the persistent file of this particular node is automatically deleted.
