### ISSUE TITLE
Node does not work when message does not have a topic

### ISSUE THREAD

**Issue by gigatexel** [Supergiovane/node-red-contrib-boolean-logic-ultimate#12]
The docs should state that a msg.topic is necessary to let the node in this repository function.

If the message does not contain a `topic` property, the message is treated as ```false```, even when the ```payload``` is set to ```true```

**Comment by Supergiovane** [comment]
Hi Giga,
from the README: 
_The node expects a fixed number of topics (configured in the settings) on which it will operate._
