### ISSUE TITLE
Reset node

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-boolean-logic-ultimate#13]
Hi, I use the node in order to evaluate the bits of a bit field (string): The bits are checked and send to the Boolean logic node serially. The node should not start until all bits are analyzed. For this I would need to delete preceding values stored in the node. A reset node function would be very useful.

**Comment by Supergiovane** [comment]
Hi Graefer,
you could use the single topic trigger. 
With this, the logic gate starts to evaluate all inputs only when that "trigger" topic arrives.
As trigger topic, you can use the last bit you extract from the string and there is no need to a reset option
In the README of github, this is explained but if you have trouble, please send here your nodes and i will check your flows.

**Comment by Supergiovane** [comment]
Hi Graefer,
is ok for you to pass a msg.reset to the boolean node that resets all inputs?
Is that what you want?

**Comment by Supergiovane** [comment]
V. 1.0.27 is out with that change.
Pass msg.reset = true (or whatever value you want) to reset all inputs to undefined.

**Comment by Supergiovane** [comment]
PS: please STAR my node. I'll very appreciate that.

**Comment by Graefer** [comment]
That‘s excellent! Thank you very much, mille grazie!
