### ISSUE TITLE
Operation of restart-persistant features?

### ISSUE THREAD

**Issue by daxliniere** [Supergiovane/node-red-contrib-boolean-logic-ultimate#14]
Hi Supergiovane,
Sorry for raising an issue ticket for this, but I couldn't find any way to contact you (I tried hard!)

I wanted to ask about how your restart-persistant features work. I [posted on the NR forum](https://discourse.nodered.org/t/how-to-avoid-gpio-transmission-on-restart/47177) about a particular flow triggering in an unwanted way when the Pi was restarted.
I'm wondering if one of your nodes would be able to solve this.

All the best,
Dax.

**Comment by Supergiovane** [comment]
Hi Dax
I’ll take a look…

**Comment by Supergiovane** [comment]
Hi Dax
The interruptflow node is what you’re searching for. 
Set it to block the flow messages at start (in the config window), then set an inject node to re-enable the message’s flow after 1 minute.

**Comment by daxliniere** [comment]
Thanks so much, Max. I really appreciate it. I'll give that a try now.

**Comment by daxliniere** [comment]
That worked a treat. Thank you very much, Max!
