### ISSUE TITLE
Not an issue, just me I guess

### ISSUE THREAD

**Issue by scottda4270** [Supergiovane/node-red-contrib-boolean-logic-ultimate#15]
Hi, been looking for a way in nodered to check multiple conditions and carry out a service call or set a boolean if certain conditions apply. Example, got some door sensors and a smart lock, want to check if they are all secure at night as part of a routine and set a 'house secure boolean'. Found your node and thought perfect but struggling to apply it.

some example code to import in as follows. Its monitoring for a state change, then uses a straighforward change node to set the boolean true or false based on what it finds in the state payload, but cant get it to trigger the 'house secure' boolean. What am i doing wrong. I would like it to set the 'house secure' boolean to on when all doors are closed and door is locked (i.e. they all return true to your boolean logic node, and in the event one returns a false then to set the 'house secure' boolean to false. (dont understand how the examples in the help would turn something off if not explicitly called)

thanks for any help you might be able to offer.
Darren

[{"id":"1a3fc91ad3aa71f0","type":"change","z":"d018ee93afce495a","name":"Set boolean output to true if front door is closed","rules":[{"t":"change","p":"payload","pt":"msg","from":"off","fromt":"str","to":"true","tot":"bool"},{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":1220,"wires":[["57ba3edf7eb09544"]]},{"id":"c051578353bd07d4","type":"change","z":"d018ee93afce495a","name":"Set boolean output to true if front door is locked","rules":[{"t":"change","p":"payload","pt":"msg","from":"locked","fromt":"str","to":"true","tot":"bool"},{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":740,"y":1300,"wires":[["57ba3edf7eb09544"]]},{"id":"57ba3edf7eb09544","type":"BooleanLogicUltimate","z":"d018ee93afce495a","name":"","filtertrue":"both","persist":true,"sInitializeWith":"WaitForPayload","triggertopic":"trigger","outputtriggeredby":"onlyonetopic","inputCount":"3","topic":"result","restrictinputevaluation":true,"x":1130,"y":1280,"wires":[["259beeb253e26f28"],[],[]]},{"id":"af21622638f7bbbc","type":"change","z":"d018ee93afce495a","name":"Set boolean output to true if back door gym left is closed","rules":[{"t":"change","p":"payload","pt":"msg","from":"off","fromt":"str","to":"true","tot":"bool"},{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":770,"y":1380,"wires":[["57ba3edf7eb09544"]]},{"id":"259beeb253e26f28","type":"api-call-service","z":"d018ee93afce495a","name":"Set house secure boolean to On","server":"2620ec24.eeb984","version":3,"debugenabled":false,"service_domain":"homeassistant","service":"turn_on","entityId":"input_boolean.house_secure","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1410,"y":1200,"wires":[[]]},{"id":"915a68bb6676e317","type":"server-state-changed","z":"d018ee93afce495a","name":"Front door open state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.front_door_sensor","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":280,"y":1220,"wires":[["1a3fc91ad3aa71f0"]]},{"id":"43ccbe6d354637bf","type":"server-state-changed","z":"d018ee93afce495a","name":"Front door lock state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"lock.front_door_smart_lock","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":270,"y":1300,"wires":[["c051578353bd07d4"]]},{"id":"2109a2fa1e242ffc","type":"server-state-changed","z":"d018ee93afce495a","name":"Gym back door left open state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.gym_back_left_door_sensor","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":300,"y":1380,"wires":[["af21622638f7bbbc"]]},{"id":"2620ec24.eeb984","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

**Comment by Supergiovane** [comment]
Hi Darren
is there a meaning on doing that multiple replacement?
<img width="526" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/139690492-d17fc5a2-d9fb-4265-8c0b-f79eda2500ca.png">

Can you please tell me, what your service node (that i haven't installed) emits as output on ? For example msg.payload = "off"  and msg.payload = "on" ? Or what? It is maybe an homeassistant node?

**Comment by Supergiovane** [comment]
Anyway,
use this flow. Attach before the function nodes and after the boolean logic node, your homeassistant nodes.

`[
    {
        "id": "adb9b463ac0a0b3b",
        "type": "function",
        "z": "fbca734997dec0b4",
        "name": "On/Off to True/False",
        "func": "return { topic: msg.topic, payload: msg.payload === \"on\" ? true : false };",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 760,
        "y": 140,
        "wires": [
            [
                "57ba3edf7eb09544"
            ]
        ]
    },
    {
        "id": "726d790e05ad419c",
        "type": "comment",
        "z": "fbca734997dec0b4",
        "name": "Set boolean output to true if front door is closed",
        "info": "",
        "x": 620,
        "y": 100,
        "wires": []
    },
    {
        "id": "dfec785291f2d62d",
        "type": "comment",
        "z": "fbca734997dec0b4",
        "name": "Set boolean output to true if front door is locked",
        "info": "",
        "x": 620,
        "y": 200,
        "wires": []
    },
    {
        "id": "b0d0f9987d4d49b5",
        "type": "comment",
        "z": "fbca734997dec0b4",
        "name": "Set boolean output to true if back door gym left is closed",
        "info": "",
        "x": 650,
        "y": 300,
        "wires": []
    },
    {
        "id": "761341e94ce0facf",
        "type": "function",
        "z": "fbca734997dec0b4",
        "name": "On/Off to True/False",
        "func": "return { topic: msg.topic, payload: msg.payload === \"on\" ? true : false };",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 760,
        "y": 240,
        "wires": [
            [
                "57ba3edf7eb09544"
            ]
        ]
    },
    {
        "id": "36f2182586d3ff99",
        "type": "function",
        "z": "fbca734997dec0b4",
        "name": "On/Off to True/False",
        "func": "return { topic: msg.topic, payload: msg.payload === \"on\" ? true : false };",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 760,
        "y": 340,
        "wires": [
            [
                "57ba3edf7eb09544"
            ]
        ]
    },
    {
        "id": "57ba3edf7eb09544",
        "type": "BooleanLogicUltimate",
        "z": "fbca734997dec0b4",
        "name": "",
        "filtertrue": "both",
        "persist": true,
        "sInitializeWith": "WaitForPayload",
        "triggertopic": "trigger",
        "outputtriggeredby": "all",
        "inputCount": "3",
        "topic": "result",
        "restrictinputevaluation": true,
        "x": 1000,
        "y": 240,
        "wires": [
            [],
            [],
            []
        ]
    }
]`

**Comment by Supergiovane** [comment]
PPS: please remember also to set a topic, because boolean logic ultimate uses a topic to count the input that has arrived. I've installed nodered on homeassistant. See here. Set a different topic for each sensor (for example, sensor1, sensor2, sensor3)

<img width="543" alt="Node-RED_-_Home_Assistant" src="https://user-images.githubusercontent.com/37666636/139696868-cea86dcd-3452-4de5-905f-39a99be67422.png">

**Comment by scottda4270** [comment]
Thanks for your quick responses @Supergiovane, much appreciated...let me try and answer your questions.

The information was coming from an home assistant node red change state node. It had a payload of 'on' or 'off' for the door sensors and 'locked' or 'unlocked' for the smart lock. That's why i put the change node in to look for 'on' or 'locked' and set the payload to true for each suggesting its secure. Each of the change state nodes already had a msg.topic based on their entity as follows

![image](https://user-images.githubusercontent.com/82318488/139714920-b031fc4e-271e-48aa-9a0f-ebf91c456c32.png)

I used the multiple replacement as i didnt really know what i was doing and was trying to follow the example, i thought it was setting the new payload to 'true' using the change node if if found the text and if it didnt then to pass the payload as 'false', i probably misunderstood the example. 

So then i pasted your code in and wrapped with my HA nodes as follows

![image](https://user-images.githubusercontent.com/82318488/139715233-e98ba6dd-d20c-4f70-a935-f6afc2baf2aa.png)

It seems to have called the boolean at the end successfully setting it to on (which for me means house is secure). I then unlocked the door hoping it would pass a false from that entity and set the boolean at the end to false...but as my previous and first note i dont know how that would ever work as i dont see anything calling a change to the boolean at the end to off. Sorry, probably being really stupid here but seems like i am so close now. 

Again thank you for your help.

**Comment by Supergiovane** [comment]
Hi
Ok thanks
You’ve set the boolean logic to single topic trigger. Please paste my code somewhere in your flow and take a look at how i set the boolean logic. Do the same. It should then work!

**Comment by scottda4270** [comment]
Hi. That last info I sent you was based on your code. It turns the Boolean on successfully but does not turn it off if one of the entities returns a false. Thanks

**Comment by Supergiovane** [comment]
You are stuck on a very simple thing. Tomorrow morning i’ll set up a sample for you, but then you need to well know how these HA nodes does work. See you tomorrow

**Comment by Supergiovane** [comment]
Hi
Disable this:
<img width="485" alt="Node-RED_-_Home_Assistant" src="https://user-images.githubusercontent.com/37666636/139735016-48e664ff-2e9a-46ee-8a30-088600d2b694.png">

I done 2 samples for you. The second one is very simple and you can test it by pushing the "Inject" buttons.
Please see that i've added the RBE node ater the boolean logic, to avoid triggering "Set house secure boolean to on" if both inputs are true.

<img width="804" alt="Node-RED_-_Home_Assistant" src="https://user-images.githubusercontent.com/37666636/139735347-9ce5afc5-7c67-4ee2-9331-bb59a271aa6e.png">

Here is the code.
Look at it and try by yourself. Use the **"Locked/Unlocked to True/False"** pink function for smart lock, and the **"On/Off to True/False"** function for doors.

`[{"id":"21375cba124bce7c","type":"function","z":"0c9389a9cb427d2b","name":"On/Off to True/False","func":"msg.payload = (msg.payload === \"on\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":300,"y":120,"wires":[["c39690eb7cf626a0"]]},{"id":"1c71ec2e35a81fc4","type":"function","z":"0c9389a9cb427d2b","name":"Locked/Unlocked to True/False","func":"msg.payload = (msg.payload === \"locked\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":330,"y":180,"wires":[["c39690eb7cf626a0"]]},{"id":"11d3f89174d25c56","type":"function","z":"0c9389a9cb427d2b","name":"On/Off to True/False","func":"msg.payload = (msg.payload === \"on\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":300,"y":240,"wires":[["c39690eb7cf626a0"]]},{"id":"c39690eb7cf626a0","type":"BooleanLogicUltimate","z":"0c9389a9cb427d2b","name":"","filtertrue":"both","persist":true,"sInitializeWith":"WaitForPayload","triggertopic":"trigger","outputtriggeredby":"all","inputCount":"3","topic":"result","restrictinputevaluation":true,"x":600,"y":180,"wires":[["e7472c71bc9e6ee3"],[],[]]},{"id":"2319db42527be628","type":"debug","z":"0c9389a9cb427d2b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":690,"y":280,"wires":[]},{"id":"e7472c71bc9e6ee3","type":"rbe","z":"0c9389a9cb427d2b","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload","topi":"topic","x":540,"y":280,"wires":[["2319db42527be628"]]},{"id":"060a6d57b9a086dd","type":"comment","z":"0c9389a9cb427d2b","name":"Sample 1","info":"","x":110,"y":80,"wires":[]},{"id":"622cfea2d4f3bd9c","type":"BooleanLogicUltimate","z":"0c9389a9cb427d2b","name":"","filtertrue":"both","persist":true,"sInitializeWith":"WaitForPayload","triggertopic":"trigger","outputtriggeredby":"all","inputCount":"3","topic":"result","restrictinputevaluation":true,"x":260,"y":440,"wires":[["011a9424e62cc065"],[],[]]},{"id":"011a9424e62cc065","type":"rbe","z":"0c9389a9cb427d2b","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload","topi":"topic","x":410,"y":440,"wires":[["18dcd28970809f7c"]]},{"id":"18dcd28970809f7c","type":"debug","z":"0c9389a9cb427d2b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":560,"y":440,"wires":[]},{"id":"351ee55c93ff879a","type":"InjectUltimate","z":"0c9389a9cb427d2b","name":"Inject","topic":"1","curVal":true,"x":90,"y":400,"wires":[[],[],["622cfea2d4f3bd9c"]]},{"id":"bfd462647da5770b","type":"InjectUltimate","z":"0c9389a9cb427d2b","name":"Inject","topic":"2","curVal":true,"x":90,"y":480,"wires":[[],[],["622cfea2d4f3bd9c"]]},{"id":"bd219e11ea91f1c7","type":"InjectUltimate","z":"0c9389a9cb427d2b","name":"Inject","topic":"3","curVal":true,"x":90,"y":560,"wires":[[],[],["622cfea2d4f3bd9c"]]},{"id":"d92148760be57371","type":"comment","z":"0c9389a9cb427d2b","name":"Sample 2 - The very simple sample.","info":"","x":180,"y":340,"wires":[]},{"id":"0135bb0445bf00fe","type":"comment","z":"0c9389a9cb427d2b","name":"The \"Inject\" node, toggles true/false","info":"","x":480,"y":340,"wires":[]}]`

**Comment by scottda4270** [comment]
Hi Max, again thanks for your persistence here...

ok so imported your code, it makes sense but it does not seem to be having the right effect in HA.

Here is my updated flow

[{"id":"d34885e97e529490","type":"comment","z":"d018ee93afce495a","name":"Set boolean output to true if front door is closed","info":"","x":620,"y":1760,"wires":[]},{"id":"0b4fc03ed0f66a8f","type":"comment","z":"d018ee93afce495a","name":"Set boolean output to true if front door is locked","info":"","x":620,"y":1860,"wires":[]},{"id":"7bafd85e47478bf2","type":"comment","z":"d018ee93afce495a","name":"Set boolean output to true if back door gym left is closed","info":"","x":650,"y":1960,"wires":[]},{"id":"2649ef2c851688c6","type":"server-state-changed","z":"d018ee93afce495a","name":"Gym back door left open state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.gym_back_left_door_sensor","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":260,"y":1980,"wires":[["fc8dcd92153a65dd"]]},{"id":"1df1e3cdd060c51b","type":"server-state-changed","z":"d018ee93afce495a","name":"Front door lock state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"lock.front_door_smart_lock","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":230,"y":1900,"wires":[["cc1766e67921ccf5"]]},{"id":"b3cef01f82062cf9","type":"server-state-changed","z":"d018ee93afce495a","name":"Front door open state","server":"2620ec24.eeb984","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.front_door_sensor","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":240,"y":1820,"wires":[["989418d24fae0cca"]]},{"id":"8ec32e9b3301635c","type":"api-call-service","z":"d018ee93afce495a","name":"Set house secure boolean to On","server":"2620ec24.eeb984","version":3,"debugenabled":false,"service_domain":"homeassistant","service":"turn_on","entityId":"input_boolean.house_secure","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":2190,"y":1860,"wires":[[]]},{"id":"115cb60f47d2fdcc","type":"switch","z":"d018ee93afce495a","name":"If all payload is true, set house secure boolean to on, if false set house secure boolean to off","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"true","vt":"str"},{"t":"eq","v":"false","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1700,"y":1920,"wires":[["8ec32e9b3301635c"],["22538ca1545cd9a5"]]},{"id":"22538ca1545cd9a5","type":"api-call-service","z":"d018ee93afce495a","name":"Set house secure boolean to Off","server":"2620ec24.eeb984","version":3,"debugenabled":false,"service_domain":"homeassistant","service":"turn_off","entityId":"input_boolean.house_secure","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":2190,"y":2000,"wires":[[]]},{"id":"7dbf17eebd8a12b6","type":"BooleanLogicUltimate","z":"d018ee93afce495a","name":"","filtertrue":"both","persist":true,"sInitializeWith":"WaitForPayload","triggertopic":"trigger","outputtriggeredby":"all","inputCount":"3","topic":"result","restrictinputevaluation":true,"x":1080,"y":1920,"wires":[["6caa4e7715161536","6b8936f4a17238dd"],[],[]]},{"id":"6caa4e7715161536","type":"rbe","z":"d018ee93afce495a","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload","topi":"topic","x":1270,"y":1920,"wires":[["115cb60f47d2fdcc"]]},{"id":"6b8936f4a17238dd","type":"debug","z":"d018ee93afce495a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1280,"y":2040,"wires":[]},{"id":"989418d24fae0cca","type":"function","z":"d018ee93afce495a","name":"On/Off to True/False","func":"msg.payload = (msg.payload === \"on\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":740,"y":1820,"wires":[["7dbf17eebd8a12b6"]]},{"id":"cc1766e67921ccf5","type":"function","z":"d018ee93afce495a","name":"Locked/Unlocked to True/False","func":"msg.payload = (msg.payload === \"locked\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":770,"y":1920,"wires":[["7dbf17eebd8a12b6"]]},{"id":"fc8dcd92153a65dd","type":"function","z":"d018ee93afce495a","name":"On/Off to True/False","func":"msg.payload = (msg.payload === \"on\" ? true : false);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":740,"y":2020,"wires":[["7dbf17eebd8a12b6"]]},{"id":"2620ec24.eeb984","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]

it looks like this graphically

![image](https://user-images.githubusercontent.com/82318488/139823336-86f6577d-579d-4339-8092-fa6bf51527ab.png)

the boolean logic node always returns a false, i put a debug node in there too to check

here are the results when all 3 inputs are true (i open and close a door to refresh the evaluation)

![image](https://user-images.githubusercontent.com/82318488/139823546-a65302b1-1d75-4798-880b-51d2b5bcd11a.png)

thank you, and if you have had enough, feel free to bail out...i appreciate your time so far!

**Comment by Supergiovane** [comment]
Hi
It can be, that some true/false in my functions must be swapped. I really doesn’t know if “on” is true or is false. 
Does “on” mean true?
Does “unlock” mean true?
Thanks

**Comment by scottda4270** [comment]
Hi
I have further simplified it just to look at the two door sensors to troubleshoot, note i have removed the connector from the door lock

![image](https://user-images.githubusercontent.com/82318488/140020502-66145ebb-b002-4317-9fc1-fce83a7858fb.png)

 I put debug on each one, one at a time to verify the output from the two function nodes are outputting true, false....they are as follows

![image](https://user-images.githubusercontent.com/82318488/140020562-6a5cce7c-0044-4205-b497-adaad8580534.png)


I have gone back to the code with the manual injects and see how yours is working fine, the boolean logic states its results below the box fine as follows

![image](https://user-images.githubusercontent.com/82318488/140020667-36a6f6be-f46a-421e-814f-421ac6545e81.png)

but when my one is run (literally copied your box over to my flow) it does not seem to evaluate all inputs including persistent states

![image](https://user-images.githubusercontent.com/82318488/140020759-18603387-de4b-4317-8fab-3cbf7a874138.png)

even though i have triggered both sensors from false to true or vice versa, the boolean logic is not evaluating as per your example. 

thanks again

**Comment by Supergiovane** [comment]
Hi
Boolean Logic node starts evaluating as soon as both TOPIC arrives.
For example, if you set the boolean logic node to evaluate 2 topics, it waits for both topics to arrive before emitting a message.
In your case, both Gym Back Door and Front Door must send their state.
In the boolean logic node status, you see "Arrived topic 1 of 2". That means that 1 topic has arrived and the other one no.
Remember: the topics must be different.
Put another debug node here and show me what message you see:
<img width="697" alt="Cursor_e_Not_an_issue__just_me_I_guess_·_Issue__15_·_Supergiovane_node-red-contrib-boolean-logic-ultimate" src="https://user-images.githubusercontent.com/37666636/140021606-d0589fcd-d1d4-4e37-be9e-5515ee040974.png">

**Comment by scottda4270** [comment]
done....
![image](https://user-images.githubusercontent.com/82318488/140032339-6d89e194-8877-4de7-88d2-a8bb0a260d79.png)

again this is issuing a payload of true or false and you can see this is working based on state. 

OK, so maybe i have misunderstood, i thought that given the persistent state it would only need one node to change for the boolean ultimate to re evaluate (thats kind of what looks to be happening in the example code you sent me with the manual injects). There will never be a situation where all 3 sensors update at the same time so the boolean node will only get one change at a time, but i was hoping that when single sensor had a changed state it evaluated that with the other persistent states (i.e. those that have not changed at the same time). 

all inbounds have separate topic names based on their origin entity name. thanks

thanks

**Comment by Supergiovane** [comment]
Hi
I need to view the topic property of the message. Not only the payload. Be sure that the two topics are different. 
And yes, the node retains the state, it is not necessary that all topics arrive at once.

**Comment by scottda4270** [comment]
Hi

here are the full debug nodes from the front door sensor in both states

![image](https://user-images.githubusercontent.com/82318488/140037933-672d43c4-c513-4ddc-a2e6-ace932bf7ab4.png)


and here are the gym door debugs

![image](https://user-images.githubusercontent.com/82318488/140038680-7e29a38b-7d93-474e-9796-c096bbebf257.png)

does this help?
thanks

**Comment by Supergiovane** [comment]
Yes. 
The topics are different and that's OK.
It should work without issues.

Let's claryfy this code you find in the functions:

`msg.payload = (msg.payload === "on" ? true : false);`
Sets the msg.payload of the output message to "true" if the input payload 
is "on", or to "false" otherwise.

`return msg;`
Outputs the message.

With that in mind, you can debug your code more easily.
If i had access to your node-red from the internet, i had done the changes in just a second...

**Comment by Supergiovane** [comment]
Please see this video. It should work!

https://user-images.githubusercontent.com/37666636/140041382-703a64bf-99fe-4086-a6a7-c39135bf44de.mov

**Comment by Supergiovane** [comment]
..and in this second video, the settings:

https://user-images.githubusercontent.com/37666636/140042187-1c6911ae-5cd9-4e40-97d7-91ff0a2ab4cf.mov

**Comment by scottda4270** [comment]
Hi Max, yep followed your videos and can see how it should be working, checked the config again and all ok. 

i have two flows that are doing the same thing but slightly different approaches now. 1st uses change node to set the true/false from the on/off or locked/unlocked...thats all working now (tested via a debug on every output in each state)

then the same but using the function node, does the same thing but using a function instead of change node. 

boolean is now evaluating, but i am getting a false on the boolean when i prove that all 3 input payloads are true (evidenced via the debug nodes on the top and bottom approach)...very strange, just cant see why it wouldnt work. 

![image](https://user-images.githubusercontent.com/82318488/140055111-f71d67ca-9114-402f-ac96-1698baeff965.png)

**Comment by Supergiovane** [comment]
Hi
you never replied to my question:
Does “on” mean true?
Does “unlock” mean true?
Or maybe vice-versa?
If vice-versa, please swap the true:false in the function, as explained here, https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/issues/15#issuecomment-958796233 or just delete the functions and use the "change" node.

**Comment by scottda4270** [comment]
Sorry for that. OK the door locks have an off or on status. When they return an off status it means they are closed. Therefore both in the function method and the change node method i am getting them to forward a true status to the boolean if they receive an off payload from the status node (i.e. off means door is shut, and therefore true should be applied ...i.e. secure. 

I have checked all the input nodes and they are all reporting correctly (i.e. 3 inbound true payloads to the boolean, but the boolean still registers a false?

for a test, i inverted the code just to check but its the same.  Its so strange as clearly your node works but i just cant fathom when i am providing 2 or 3 true statements (tried to simplify just with the two), it still returns a false.

Payloads are both returning a false (the two door locks)

![image](https://user-images.githubusercontent.com/82318488/140075032-84470b0a-537a-4149-b271-46f24f669d8e.png)

the boolean is only evaluating these two inputs but returns a false instead of a true

![image](https://user-images.githubusercontent.com/82318488/140075251-1076ba2a-1005-40fd-9ac4-04868126f71f.png)

I dont think i can strip any more of it out to make its simper to fault find, but its a real strange one?

**Comment by Supergiovane** [comment]
Hi
Ok, so for door open (the first and third blue nodes), please replace
`msg.payload = (msg.payload === "on" ? true : false);`
with 
`msg.payload = (msg.payload === "on" ? false : true);`
in both the two function.

With that, if both the doors are closed, they send an "off" command, so  both the function nodes returns "true".
The boolean logic also will return true.
Please try and let me know.

**Comment by scottda4270** [comment]
Right, have applied those changes you suggested....

something very strange is happening...have noticed the boolean does in fact return a true payload...but get this..

![image](https://user-images.githubusercontent.com/82318488/140163193-77aca5cb-a8bc-4419-a8dd-c96db1b1d4a7.png)

only when one door is open and one is shut (or one is off and the other is on, meaning one true and one false)

this is confirmation of the front door sensor code in the inverted state

![image](https://user-images.githubusercontent.com/82318488/140163365-95461756-9259-4078-b3c8-c7e592eb3b78.png)

and here is the gym door code in the inverted state

![image](https://user-images.githubusercontent.com/82318488/140163457-91e17d55-f401-42f7-b796-e03a115121b4.png)


totally confused now.

**Comment by Supergiovane** [comment]
Hi
The Gym door is not inverted. Swap true : false with false : true

**Comment by scottda4270** [comment]
wow...how did that happen? i literally cut and paste it from the other...quite right and guess what...all working now!!! Thank you so much Max for your perseverance, also bought the smart lock in as well now and inverted the function code. really appreciate all of your help and will now scale this out to do what i had originally intended by using in an end of day function to check the house and car is secure. THANK YOU!!!!!!

**Comment by Supergiovane** [comment]
I’m pleased to help good people. 
If you need more help, just ask.
;-)
