### ISSUE TITLE
Blinker no output on start

### ISSUE THREAD

**Issue by wde-360** [Supergiovane/node-red-contrib-boolean-logic-ultimate#16]
Hi I have just found your set of logic nodes and have a use for the blinker node. I wish to use it as a timer that produces a 30 minute on 30 minute off sequence, the problem is at the first switch on the output does not go true until it times out at the end of 30 minutes. In the nodes intended use as a led blinker this would not matter, I just wondered if this could be changed or set as an option. The icing on the cake would be to allow the on off periods to be independently set, maybe an idea for another node?

**Comment by Supergiovane** [comment]
Hi
Ok, i'll put an option like "Start with true" and "Start with false".
As far as  for the independent ON/OFF, i must give it a look...
The updated version should be out in about 30 minutes...

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-boolean-logic-ultimate@1.0.36 is out.
Please use the ImpulseUltimate node.
I've added the "repeat" command to repeat the sequence. Please see the README on github for further explanation and... star my node!

**Comment by wde-360** [comment]
Thank you so much for the quick response, works a treat, you certainly live up to the Super in your name!!
