### ISSUE TITLE
BooleanLogicUltimate

### ISSUE THREAD

**Issue by jftheoret** [Supergiovane/node-red-contrib-boolean-logic-ultimate#18]
I have just updated to the latest BooleanLogicUltimate plugin version (along with the latest Node Red version) and I get an error:

16 Nov 08:47:36 - [error] [BooleanLogicUltimate:686cc14f.8aa3e] TypeError: value.toLowerCase is not a function

Node Red version is 2.1.3
node-red-contrib-boolean-logic-ultimate is 1.0.38

**Comment by Supergiovane** [comment]
Hi,
you're passing a number to the node, instead of true/false.
You can either enable the "Reject non boolean..."
<img width="433" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/142001134-3e875663-c8d5-4ba6-a8e7-daf4830b72c2.png">

or wait for a fix (about 1 hour).

**Comment by jftheoret** [comment]
Thank you very much!! I have reverted back to 1.0.36 for now.

I will wait for your fix.

BTW thanks for these great nodes!!

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.0.39 is out in about 15 minutes.

**Comment by Supergiovane** [comment]
Thank you to you, to raising this issue!
