### ISSUE TITLE
State retention doesn't propogate correctly

### ISSUE THREAD

**Issue by xAPPO** [Supergiovane/node-red-contrib-boolean-logic-ultimate#2]
I have created 12 seven input booleans and connected all the 'AND' outputs of these to one further 12 input 'checkgate'  and I'm monitoring the  OR output  which warns me if non of the other 12 gates are matching . 

Each of the 12 gates has input state retention and when restarted that shows correctly and gives the correct output on each gate.  So the single output 'check gate' should now have all valid inputs and give a valid output - but it doesn't - it shows 'awaiting input'.    I have not used state retention on this gate as it shouldn't be needed (as all gates that input to this have retention on their respective inputs)

**Comment by Supergiovane** [comment]
Hello xAPPO
please paste here your flow export. Then i’ll check it for you. 
Are you able to do that? Select all nodes involved in your problem, then select “export” from the node-red menu, then paste here the exported nodes. 
Thanks

**Comment by xAPPO** [comment]
[{"id":"8c79754d.fc1d28","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":360,"wires":[]},{"id":"aa329929.46fc88","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Eight","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":660,"wires":[["a0721e47.1aac8","a33ca76f.8ccbe8"],[],[]]},{"id":"86513cac.d83bc","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 1","topic":"cbus/read/254/56/241/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":40,"wires":[["90d458c4.7e6ce8","57c404c4.e2388c","5d6a876.8e15d78"]]},{"id":"aff128ac.b979f8","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 2","topic":"cbus/read/254/56/242/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":120,"wires":[["a6e4706f.4cb82","3b927ac4.ff4916","ff649093.d44d9","90d458c4.7e6ce8","6ef6bd5b.e28964","ff6b4b8c.b471d8"]]},{"id":"77714663.13c408","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 3","topic":"cbus/read/254/56/243/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":200,"wires":[["949a1835.61be68","e1f4f74f.f5bd28","3e293fc7.683e","ff6b4b8c.b471d8"]]},{"id":"ecb21ad.877b4e8","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 4","topic":"cbus/read/254/56/244/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":280,"wires":[["90d458c4.7e6ce8","949a1835.61be68","3b927ac4.ff4916","221ef241.debb5e","f527a931.1f8598"]]},{"id":"30fd8293.5eb57e","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 5","topic":"cbus/read/254/56/245/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":360,"wires":[["90d458c4.7e6ce8","949a1835.61be68","3b927ac4.ff4916","1f66ef05.01ef41","57c404c4.e2388c","17a7de18.089322","6ef6bd5b.e28964"]]},{"id":"b4619fee.441fc","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 6","topic":"cbus/read/254/56/246/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":440,"wires":[["a6e4706f.4cb82","949a1835.61be68","e1f4f74f.f5bd28","e08b7908.d3fbc8"]]},{"id":"70de583.11bdca8","type":"mqtt in","z":"94b6097c.f101d8","name":"Boiler LED 7","topic":"cbus/read/254/56/247/level","qos":"2","datatype":"auto","broker":"7a7c4d0.63c8ab4","x":150,"y":520,"wires":[["90d458c4.7e6ce8","949a1835.61be68","3b927ac4.ff4916","57c404c4.e2388c","55a3361.b89e2c8"]]},{"id":"949a1835.61be68","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Six","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":420,"wires":[["3c43ee7f.81a3a2","a33ca76f.8ccbe8"],[],[]]},{"id":"57c404c4.e2388c","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Four","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":300,"wires":[["4dea9b11.5ccd74","a33ca76f.8ccbe8"],[],[]]},{"id":"6ef6bd5b.e28964","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Three","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":240,"wires":[["46348353.57ac3c","a33ca76f.8ccbe8"],[],[]]},{"id":"ff6b4b8c.b471d8","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Five","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":360,"wires":[["1eaa764c.6f491a","a33ca76f.8ccbe8"],[],[]]},{"id":"a6e4706f.4cb82","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Two","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":180,"wires":[["a8e1e903.d8e1e8","a33ca76f.8ccbe8"],[],[]]},{"id":"3b927ac4.ff4916","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Seven","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":710,"y":480,"wires":[["c603a163.0d6ba","a33ca76f.8ccbe8"],[],[]]},{"id":"1f66ef05.01ef41","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Nine","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":600,"wires":[["b715e75e.aa6548","a33ca76f.8ccbe8"],[],[]]},{"id":"e1f4f74f.f5bd28","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Error","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":620,"y":980,"wires":[["e591a96c.5109e8","a33ca76f.8ccbe8"],[],[]]},{"id":"bdc1fb39.859b98","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"All Off","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":710,"y":720,"wires":[["858d9ac4.002428","a33ca76f.8ccbe8"],[],[]]},{"id":"90d458c4.7e6ce8","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"One","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":120,"wires":[["bef8e068.1ee45","a33ca76f.8ccbe8"],[],[]]},{"id":"5d6a876.8e15d78","type":"Invert","z":"94b6097c.f101d8","name":"! LED1","x":230,"y":640,"wires":[["a6e4706f.4cb82","3b927ac4.ff4916","949a1835.61be68","e1f4f74f.f5bd28","1f66ef05.01ef41","bdc1fb39.859b98","aa329929.46fc88","6ef6bd5b.e28964","ff6b4b8c.b471d8","f527a931.1f8598"]]},{"id":"ff649093.d44d9","type":"Invert","z":"94b6097c.f101d8","name":"! LED2","x":130,"y":700,"wires":[["57c404c4.e2388c","949a1835.61be68","e1f4f74f.f5bd28","1f66ef05.01ef41","bdc1fb39.859b98","aa329929.46fc88","ff6b4b8c.b471d8","f527a931.1f8598"]]},{"id":"221ef241.debb5e","type":"Invert","z":"94b6097c.f101d8","name":"! LED4","x":230,"y":760,"wires":[["a6e4706f.4cb82","57c404c4.e2388c","e1f4f74f.f5bd28","1f66ef05.01ef41","bdc1fb39.859b98","aa329929.46fc88","6ef6bd5b.e28964","ff6b4b8c.b471d8"]]},{"id":"3e293fc7.683e","type":"Invert","z":"94b6097c.f101d8","name":"! LED3","x":310,"y":700,"wires":[["a6e4706f.4cb82","57c404c4.e2388c","3b927ac4.ff4916","90d458c4.7e6ce8","1f66ef05.01ef41","bdc1fb39.859b98","aa329929.46fc88","6ef6bd5b.e28964","f527a931.1f8598"]]},{"id":"17a7de18.089322","type":"Invert","z":"94b6097c.f101d8","name":"! LED5","x":130,"y":820,"wires":[["a6e4706f.4cb82","e1f4f74f.f5bd28","bdc1fb39.859b98","aa329929.46fc88","f527a931.1f8598"]]},{"id":"e08b7908.d3fbc8","type":"Invert","z":"94b6097c.f101d8","name":"! LED6","x":330,"y":820,"wires":[["90d458c4.7e6ce8","57c404c4.e2388c","3b927ac4.ff4916","bdc1fb39.859b98","1f66ef05.01ef41","aa329929.46fc88","6ef6bd5b.e28964","ff6b4b8c.b471d8","f527a931.1f8598"]]},{"id":"55a3361.b89e2c8","type":"Invert","z":"94b6097c.f101d8","name":"! LED7","x":230,"y":880,"wires":[["a6e4706f.4cb82","e1f4f74f.f5bd28","bdc1fb39.859b98","aa329929.46fc88","6ef6bd5b.e28964","1f66ef05.01ef41","ff6b4b8c.b471d8","f527a931.1f8598"]]},{"id":"6c46531d.4f693c","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":60,"wires":[]},{"id":"afade1b9.7efed","type":"function","z":"94b6097c.f101d8","name":"0","func":"if (msg.payload===true) msg.payload=0\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":60,"wires":[["6c46531d.4f693c"]]},{"id":"9657fc4b.7d49b","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":420,"wires":[]},{"id":"3c43ee7f.81a3a2","type":"function","z":"94b6097c.f101d8","name":"6 Hot Water","func":"if (msg.payload===true) msg.payload=6\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":930,"y":420,"wires":[["9657fc4b.7d49b"]]},{"id":"f2328906.f586e8","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":480,"wires":[]},{"id":"c603a163.0d6ba","type":"function","z":"94b6097c.f101d8","name":"7 Heating","func":"if (msg.payload===true) msg.payload=7\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":920,"y":480,"wires":[["f2328906.f586e8"]]},{"id":"35400b2d.ca0464","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":300,"wires":[]},{"id":"4dea9b11.5ccd74","type":"function","z":"94b6097c.f101d8","name":"4","func":"if (msg.payload===true) msg.payload=4\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":300,"wires":[["35400b2d.ca0464"]]},{"id":"a2909fb4.d1d6f","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":240,"wires":[]},{"id":"46348353.57ac3c","type":"function","z":"94b6097c.f101d8","name":"3","func":"if (msg.payload===true) msg.payload=3\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":240,"wires":[["a2909fb4.d1d6f"]]},{"id":"e3d20f1a.a36bb","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":540,"wires":[]},{"id":"a0721e47.1aac8","type":"function","z":"94b6097c.f101d8","name":"8","func":"if (msg.payload===true) msg.payload=8\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":540,"wires":[["e3d20f1a.a36bb"]]},{"id":"503b242c.82fe8c","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":660,"wires":[]},{"id":"e591a96c.5109e8","type":"function","z":"94b6097c.f101d8","name":"Error","func":"if (msg.payload===true) msg.payload='Error'\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":660,"wires":[["503b242c.82fe8c"]]},{"id":"1de9969.e6bee69","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":720,"wires":[]},{"id":"858d9ac4.002428","type":"function","z":"94b6097c.f101d8","name":"Blank (Flashing)","func":"if (msg.payload===true) msg.payload=FLASH\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":920,"y":720,"wires":[["1de9969.e6bee69"]]},{"id":"9da8cc34.59725","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":600,"wires":[]},{"id":"b715e75e.aa6548","type":"function","z":"94b6097c.f101d8","name":"9","func":"if (msg.payload===true) msg.payload=9\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":600,"wires":[["9da8cc34.59725"]]},{"id":"1eaa764c.6f491a","type":"function","z":"94b6097c.f101d8","name":"5","func":"if (msg.payload===true) msg.payload=5\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":360,"wires":[["8c79754d.fc1d28"]]},{"id":"a52af06f.711be","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":180,"wires":[]},{"id":"a8e1e903.d8e1e8","type":"function","z":"94b6097c.f101d8","name":"2","func":"if (msg.payload===true) msg.payload=2\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":180,"wires":[["a52af06f.711be"]]},{"id":"697208ca.08bcc8","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":120,"wires":[]},{"id":"bef8e068.1ee45","type":"function","z":"94b6097c.f101d8","name":"1","func":"if (msg.payload===true) msg.payload=1\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":910,"y":120,"wires":[["697208ca.08bcc8"]]},{"id":"a33ca76f.8ccbe8","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Unexpected","filtertrue":"both","persist":false,"inputCount":"12","topic":"number","x":650,"y":860,"wires":[[],["fc86cfdf.cce02"],[]]},{"id":"e663e98f.e4be08","type":"mqtt out","z":"94b6097c.f101d8","name":"Boiler LED number","topic":"Boiler/LED","qos":"1","retain":"true","broker":"b3df48e4.f76a28","x":1110,"y":780,"wires":[]},{"id":"fc86cfdf.cce02","type":"function","z":"94b6097c.f101d8","name":"None of Above","func":"if (msg.payload===true) msg.payload='Unexpected'\nelse return\nreturn msg;","outputs":1,"noerr":0,"x":920,"y":780,"wires":[["e663e98f.e4be08"]]},{"id":"f527a931.1f8598","type":"BooleanLogicUltimate","z":"94b6097c.f101d8","name":"Zero","filtertrue":"both","persist":true,"inputCount":"7","topic":"number","x":700,"y":60,"wires":[["afade1b9.7efed"],[],[]]},{"id":"b3df48e4.f76a28","type":"mqtt-broker","z":"","name":"HASS 78","broker":"192.168.1.78","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"15","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"7a7c4d0.63c8ab4","type":"mqtt-broker","z":"","broker":"localhost","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"15","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","willTopic":"","willQos":"0","willPayload":""}]

**Comment by xAPPO** [comment]
It may be a topic thing...  it's a half implemented flow so...

What I'm basically trying to do is convert 8 (well actually 7) MQTT sourced binary inputs into a number - maybe there's something else that's better.  The inputs are a 7 segment LED display numbered

   1
2    3
   4
5    6
   7

So 1 3 and 6 ON is a 7      (inverted in my implementation)

**Comment by Supergiovane** [comment]
I’ll try tomorrow but i can see that many logic nodes does have the same topic. Each logic node must have a different topic so the next logic node can evaluates the inputs based on these topics.

**Comment by xAPPO** [comment]
OK let me change that and try

**Comment by Supergiovane** [comment]
The logic node expects a total of topics you set in the configuration, for example 2 or 12. 
The only way to understand who has passed a payload, is to check the topic. Once the logic receives a number of different topics set in the configuration, it starts to evaluate the inputs and it output the results. The basic default logic module that you find in the npm repo, is working so as well.
