### ISSUE TITLE
Feature request: INTERRUPT FLOWS ULTIMATE flush command

### ISSUE THREAD

**Issue by Darkman1900** [Supergiovane/node-red-contrib-boolean-logic-ultimate#20]
In addition to the play command I would need a flush command. 
Often I want to send a message only once after it was blocked by the interrupt node.
Would be a great extension of your package to make many flows easier.
Thank you
Best regards

**Comment by Supergiovane** [comment]
Hi Darkman.
Can you provide ad example, to better understand? What should the flush command do? Must it clear the stored value?

**Comment by Darkman1900** [comment]
Hi, similar to the "delay node" but in my usecase two ways would be ok. 
1. like your play command but send the stored value and clear it afterwards
2. a reset command to clear the last stored value 
3. extended wish: really like the flush from the delay node: send all stored values and clear it afterwards 
Hope that helps
Thank you for your really fast repley

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.0.46 is put with the "reset" property.
See the README on github
The 3. point cannot be achieved, because the node won't store all messages, but only the last one.
