### ISSUE TITLE
Add instructions directly in node

### ISSUE THREAD

**Issue by MarshallCS** [Supergiovane/node-red-contrib-boolean-logic-ultimate#22]
Please put all of the instructions in the nodes itself instead of making us come to the github page.
I love your tools, but this is quite annoying

**Comment by Supergiovane** [comment]
Hi Marshall
I've done that at the beginning, but the simplicity of the "help" tab in Node-Red, is insufficient.
In the Readme on github you'll see screenshot, samples, pieces of code, and you've even access to the youtube channel, with explanatory videos.
I think you'll must live with that :-)

**Comment by MarshallCS** [comment]
Can you at least do the basic instructions, and also have the GitHub page? This is all I get now  From: SupergiovaneSent: Tuesday, May 31, 2022 10:52 AMTo: Supergiovane/node-red-contrib-boolean-logic-ultimateCc: MarshallCS; AuthorSubject: Re: [Supergiovane/node-red-contrib-boolean-logic-ultimate] Add instructions directly in node (Issue #22) Hi MarshallI've done that at the beginning, but the simplicity of the "help" tab in Node-Red, is insufficient.In the Readme on github you'll see screenshot, samples, pieces of code, and you've even access to the youtube channel, with explanatory videos.I think you'll must live with that :-)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Supergiovane** [comment]
Hi again
nope sorry, in this case i should do the work twice, in the Node-Red tab and on github.
I mantain many nodes, one of that (KNX-Ultimate) in italian, german, english and chinese language. Every time i made a change, i need to update the entire wiki in all languages.
Sorry but i've not so many time to spend in a free and open source project.
But... once learned, boolean logic ultimate is very simple to use and remember.

**Comment by MarshallCS** [comment]
Can you at least do the basic instructions, and also have the GitHub page? This is all I get now  From: SupergiovaneSent: Tuesday, May 31, 2022 10:52 AMTo: Supergiovane/node-red-contrib-boolean-logic-ultimateCc: MarshallCS; AuthorSubject: Re: [Supergiovane/node-red-contrib-boolean-logic-ultimate] Add instructions directly in node (Issue #22) Hi MarshallI've done that at the beginning, but the simplicity of the "help" tab in Node-Red, is insufficient.In the Readme on github you'll see screenshot, samples, pieces of code, and you've even access to the youtube channel, with explanatory videos.I think you'll must live with that :-)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Supergiovane** [comment]
Hi Marshall
This has already been done. Please upgrade.
