### ISSUE TITLE
Keep message properties

### ISSUE THREAD

**Issue by soenkegissel** [Supergiovane/node-red-contrib-boolean-logic-ultimate#23]
My input message has some custom properties:

msg.payload.person = "Paul"
msg.payload.presence = true

Is there a way to keep these properties? The msg.payload after the node is just true / false.

**Comment by Supergiovane** [comment]
Hi
No. The node must output a payload that is true or false. 
You can move your original payload to another property, for example msg.originalpayload, before sending the message to the boolean logic node. In this manner, your original payload will be retained n

**Comment by soenkegissel** [comment]
Alright. I wasn't aware of setting custom top level properties, which are not overwritten, like
msg.presence.person = "Paul"
msg.presence.time = 2022/09/01...
Thanks for helping.
