### ISSUE TITLE
Filter node doesn't work for me anymore

### ISSUE THREAD

**Issue by kolbenhans** [Supergiovane/node-red-contrib-boolean-logic-ultimate#24]
Hi there, since last update to version 1.0.55, the filter nodes i use to convert my iobroker output from "true","false", "1","0", "open","close" etc. is not working anymore.

inputs of string true/false as well as strings 1/0 shows the error message:
"Receive non convertable boolean value from....."

i also teste it with stupid inject nodes with "true" and "false" in msg.payload, but same error does appear.

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-boolean-logic-ultimate@1.0.56 is out with a fix for the issue.
Sorry for that.
Cheers.

**Comment by kolbenhans** [comment]
> Hi node-red-contrib-boolean-logic-ultimate@1.0.56 is out with a fix for the issue. Sorry for that. Cheers.

Yeah, works like a charm. Thank you!
