### ISSUE TITLE
Time in Status

### ISSUE THREAD

**Issue by bdydrp** [Supergiovane/node-red-contrib-boolean-logic-ultimate#25]
Where does the node get is time from to display?
![image](https://user-images.githubusercontent.com/63593828/189117984-dd355de7-5e54-4318-b116-9b664dc35c67.png)

The time shown in the status is not my current time

Thanks

**Comment by Supergiovane** [comment]
Hi
Date.getDate() and Date.toLocaleTimeString()
You need to correctly set your local time settings on your system.
