### ISSUE TITLE
Node documentation / instructions within NR

### ISSUE THREAD

**Issue by alexruffell** [Supergiovane/node-red-contrib-boolean-logic-ultimate#26]
It is quite frustrating to use your awesome nodes because there is absolutely no information on what each node does without coming here!

<img width="388" alt="image" src="https://user-images.githubusercontent.com/4006944/189491950-867d589d-6eba-4fbc-a1f0-c79f62481c5c.png">

Please add a minimal description here explaining what each node is for. While I am NOT a fan of having to come to GitHub for all help, I understand that providing the information within node red may be limiting... but there is so much wasted room here too:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/4006944/189492004-3d8961e6-3ca5-4bbc-b682-f7f2670b29ce.png">

...it would be very helpful to have something, a minimal set of instructions, within Node Red and the full documentation on GitHub.

**Comment by Supergiovane** [comment]
Fixed all in the 1.0.57.
Ciao.
