### ISSUE TITLE
BooleanLogicUltimate - text not legible due to white over green color scheme

### ISSUE THREAD

**Issue by alexruffell** [Supergiovane/node-red-contrib-boolean-logic-ultimate#28]
I imagine that the issue arises from the use of the popular Dark Theme. The text is white over light green so you can only read it if you highlight it first:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/4006944/189492608-4f48a250-5aeb-45fc-84b3-1f414e5c72a2.png">

<img width="410" alt="image" src="https://user-images.githubusercontent.com/4006944/189492658-ff588172-9b30-4bd8-aef4-a0c6e9d2ff85.png">

**Comment by Supergiovane** [comment]
Fidex
