### ISSUE TITLE
Typo in FILTER ULTIMATE documentation

### ISSUE THREAD

**Issue by alexruffell** [Supergiovane/node-red-contrib-boolean-logic-ultimate#29]
This:
```
If the input payload is true, the node will send true on output 1 and nothing on oputput 2
If the input payload is false, the node will send nothing on output 1, and false on oputput 2
```

should be:

```
If the input payload is true, the node will send true on output 1 and nothing on output 2
If the input payload is false, the node will send nothing on output 1, and false on output 2
```

<img width="676" alt="image" src="https://user-images.githubusercontent.com/4006944/189493300-67b146ba-fe9b-44f1-97c7-5c21d1917e36.png">

**Comment by Supergiovane** [comment]
Both sentences are identical. Al least, i' ve checked twice and they seems the same.

**Comment by alexruffell** [comment]
Lol, I had to read it several times too to find the issue again:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/4006944/190461912-34e14c26-a5ea-44e8-b493-eade7196e8aa.png">

`oputput` should be `output` in both sentences.

**Comment by Supergiovane** [comment]
Hi Alex
Ok, catched.
The changes have effects with the upcoming .58 release. Thanks.
