### ISSUE TITLE
Arrived topic 1 of 2

### ISSUE THREAD

**Issue by Mislancer** [Supergiovane/node-red-contrib-boolean-logic-ultimate#3]
Hello,

I try to make use off your logic function in node-red. But for some reason i can not make it work. I have two boolean values with different topics connected at the input of your function. See the picture below. For some reason, i cannot explain, its keep saying arrived topic 1 of 2. I must be doing something wrong but i have no clue of what it would be. I hope you can help me out. Thank you.

![afbeelding](https://user-images.githubusercontent.com/3470747/66869388-93cc7780-ef9f-11e9-8dfe-3f4325de5882.png)

![afbeelding](https://user-images.githubusercontent.com/3470747/66869907-a85d3f80-efa0-11e9-9278-8ad76ad51290.png)

![afbeelding](https://user-images.githubusercontent.com/3470747/66870228-451fdd00-efa1-11e9-95ad-53ea44e43b88.png)

![afbeelding](https://user-images.githubusercontent.com/3470747/66870271-5832ad00-efa1-11e9-9c71-36cfd03d4e84.png)

![afbeelding](https://user-images.githubusercontent.com/3470747/66869976-c9259500-efa0-11e9-9e67-a35ea2e433d0.png)

**Comment by Mislancer** [comment]
Good morning,

So discovered what i was doing wrong. I had an empty topic and didn't set the topic (see picture). Setting it solved my problem, now everything is working. 
I'm so free to do a small suggestion. In the info of the function maybe add a couple of sentence about that on the input side every input has to have a different topic. For a novice like me that would have help. For the rest of it thanks for your hard work.

![afbeelding](https://user-images.githubusercontent.com/3470747/66889568-335f2980-efe3-11e9-826f-81bfd0546c94.png)

**Comment by Supergiovane** [comment]
Hello Mislancer.
Thank you for the suggestion!
