### ISSUE TITLE
Typos in INJECT ULTIMATE / STATUS ULTIMATE

### ISSUE THREAD

**Issue by alexruffell** [Supergiovane/node-red-contrib-boolean-logic-ultimate#30]
`pourpose` should be `purpose`

I believe you use `output` everywhere else, so I would recommend replacing `pin` with `output` 

```
The pourpose of this node is to send a message with payload TRUE on the first pin, FALSE on second pin and a TOGGLE (true/false) on the third pin, by pressing the pushbutton.
This is useful if you need to simply test your flow. The node is simpler as the default node-red inject node.
```

I am not sure what you mean by `The node is simpler as the default node-red inject node.`

"Il nodo e' semplice come il nodo standard 'inject' di node-red" ? (This node is as simple as the default node-red inject node)
"Il nodo e' piu' semplice del nodo standard 'inject' di node-red" ? (This node is simpler than the default node-red inject node)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/4006944/189493410-dc503aea-ff46-4599-a73e-41340d47525f.png">

**Comment by Supergiovane** [comment]
Hi
thank you for pointing me out all these issues. I'll check it as soon as i've some spare time.
It't wonderful if you can do the changes by yourself and do a PR, so you'll become an active contributor. :-)

**Comment by alexruffell** [comment]
@Supergiovane I would be glad to but first I will have to learn how to do it.

(Un saluto dal Texas. Sono cresciuto a Roma ma vivo in TX da 20 anni circa.)

**Comment by Supergiovane** [comment]
Ciao Alex. Potevi dirlo subito! In fine settimana appena trovo il tempo faccio le modifiche. 
C’è un altro romano che è venuto in Texas e che ogni tanto mi capita di vedere su YouTube. Si chiama Claudio.
