### ISSUE TITLE
Suggestion: case insensitive

### ISSUE THREAD

**Issue by cconde** [Supergiovane/node-red-contrib-boolean-logic-ultimate#31]
I have a Tasmota device that can't work with your module because it sends "ON" and "OFF".

Could you please lowercase the input before testing to cover such cases, and maybe other as "On", "Off"...

**Comment by Supergiovane** [comment]
Hi
I'll take a look...

**Comment by Supergiovane** [comment]
There is already such function.

```
 if (value.toLowerCase() === "on") return true;
        if (value.toLowerCase() === "off") return false;
```

 Have you updated to the latest versione?
