### ISSUE TITLE
Boolean Logic hits cpu hard

### ISSUE THREAD

**Issue by TheBartoMan** [Supergiovane/node-red-contrib-boolean-logic-ultimate#32]
Ive spent a few days figuring out what is hitting my CPU hard.

Turns out its the Boolean Logic module.

Changed it for the node-red-contrib-boolean-logic and my CPU has dropped from 100% to 20%

**Comment by Supergiovane** [comment]
Hi Barto
I wish i can take a look to your flow, because i’ve never experienced anything like that. 
The boolean logic uktimate node does write to the disk to retain the states. Does nodered have the rights to write into its folder?

**Comment by TheBartoMan** [comment]
I don't have it in the flow now as I replaced with the standard boolean, but it was nothing special. Just four separate topics feeding true or false into the Boolean Logic Ultimate Node.

**Comment by Supergiovane** [comment]
Hi Barto
I've thousand of users using my node and no one has ever reported that, so i wish to investigate by myself into it.
Can you please tell me your OS (windows, debian, ecc), node version (you can issue **node -v** from a command prompt ) and your node-red version?
Thanks.
