### ISSUE TITLE
FALSE AND FALSE

### ISSUE THREAD

**Issue by dodther** [Supergiovane/node-red-contrib-boolean-logic-ultimate#34]
Hi. In some automations, I need to perform actions when several devices are turned off. but false and false == false. And the logic doesn't work. I have to additionally invert the signals. Can you add the ability to invert signals in your logic?

**Comment by Supergiovane** [comment]
Hi Dother
You can use the "Invert Ultimate" node for that, that is part of the boolean logic module set.
