### ISSUE TITLE
Enhancement request: Override for input count field in logic gates

### ISSUE THREAD

**Issue by MaxVonEvil** [Supergiovane/node-red-contrib-boolean-logic-ultimate#35]
Hi there,
I am using an OR gate in a subflow where I expect to have varying number of array elements to process through a split node. Unless I've overlooked something it seems that the Input count field cannot be set dynamically

Would like to suggest either support for a msg.gatecount or similar where one could specify the number of inputs the node should expect. Alternatively if the input count field supported a {{count}} mustache template, that would work fine as well.

Thanks a bunch for your stellar work!

**Comment by Supergiovane** [comment]
Hi Max
Good idea.
I start to work on the msg.gatecount instantly. Expect an update version in about 1 hour.

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.0.59 is out. The property is named **msg.inputcount**
Please try it and let me know if it fits your needs. Thanks.

**Comment by MaxVonEvil** [comment]
Hi Massimo, pardon the deferred reply - regular work got in the way :) I just tested the update from yesterday and msg.inputcount works exactly as one could have hoped for. 
 - Thanks for the quick update and keep up the great work!

PS: Here is an json export of a subflow I created around your node if others find it useful: https://pastebin.com/mNcJeh0z
