### ISSUE TITLE
Enhancement Request: ability to enhance the list of compatible input values and their mapping to true:false

### ISSUE THREAD

**Issue by VanillaFord** [Supergiovane/node-red-contrib-boolean-logic-ultimate#37]
Hi there,
I am using your nodes to integrate input from different devices, 

As the input values for the nodes need to match a boolean value, the - currently statically defined - list does help, but does not cater for all possible use-cases.
Therefore I suggest to enhance the input matching feature with a user defined list of values that will be mapped to boolean values true:false.

That list could be enabled to be entered in the node property by the user, maybe similar to rules in a change or switch node.
Another option would be to keep/change the mapping table in a flow/system-wide configuration node, then used by all nodes in the flow / installation - maybe its usage can even be made switchable (on/off) in each node.

Thanks in advance for considering and thank you for your fine contribution to the node red community!
regards,
Ford

**Comment by Supergiovane** [comment]
Hi Ford,
I'm already working on that. Thank you for the suggestions. I'll keep you informed as soon as the new version is out.

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.1.0 is out.
There is a new "translator-config" node, you can use to add your own translation.
Please try it and let me know if it fits your needs.

**Comment by VanillaFord** [comment]
@Supergiovane v1.1.0 with the new translation-config works like charme...thank you very much for your speedy upgrade
