### ISSUE TITLE
MathUltimate Node always returns measurements: 0 when using "substract" operation

### ISSUE THREAD

**Issue by VanillaFord** [Supergiovane/node-red-contrib-boolean-logic-ultimate#40]
Hi there,

I am testing the MathUltimate Node with the substract operation and feeding in two different topics.
While the resulting payload seems to be fine, the measurements part of the message object is always reported as 0 (zero)
In my use case this is a minor problem but might be a major issue for others.

thanks for considering

regards,
ford

**Comment by Supergiovane** [comment]
Hi
I'll check immediately...

**Comment by Supergiovane** [comment]
Hi,
You're right.
Thank you!!!!

V. 1.1.1 is out now.
