### ISSUE TITLE
Gate Node not outputting false anymore

### ISSUE THREAD

**Issue by Qonstrukt** [Supergiovane/node-red-contrib-boolean-logic-ultimate#41]
I have a Gate 2 in my flow which used to work perfectly fine with two input nodes that could return true or false. But since I've upgraded to version 1.1.1 it no longer returns `false` when both inputs return `false` as their initial values.

This is with the Filter output setting set to output both `true` and `false` of course. And I've debugged both input nodes to still return the proper values, and they do.

**Comment by Supergiovane** [comment]
Hi,
have you tried to delete the node and add a new one from scratch?

**Comment by Qonstrukt** [comment]
Yes, I actually did, unfortunately it made no difference.

**Comment by Supergiovane** [comment]
I’ll take a look, but mine works flawlessy. 
In the meantime, check wether the two msg.topic differ each other.

**Comment by Supergiovane** [comment]
Hi, 
in the first video, the gate sends FALSE if both topics (the two upper and lower inject nodes, with topic "1" and "2".
https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/37666636/2e9182f1-fe77-4049-86ad-009b03cc3ab0

Here, i've set the gate to initialize itself with "false" at boot.
The value "false" works well.
https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/37666636/5797c3eb-40ab-40ab-aa21-5896dedaf421

If you send me your flow, i can check it.
