### ISSUE TITLE
Comparator: Operation < or > says true on same input

### ISSUE THREAD

**Issue by DerOeli** [Supergiovane/node-red-contrib-boolean-logic-ultimate#44]
When using the > or < operation in the comparator node while having the same number as input for topic 'a' and topic 'b' the result is true.

Obviously it should say false, because 1 is not bigger or smaller than 1.

![image](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/58918072/e17763ad-75c3-4dfd-935f-a859cc0e4d43)

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.1.8 is out with the fix.
Thanks.
