### ISSUE TITLE
MathUltimate Substract result always in "wait for msg.topic"

### ISSUE THREAD

**Issue by Sectorchan** [Supergiovane/node-red-contrib-boolean-logic-ultimate#45]
Hi,

I want to substract, similiar to the multiply and Sum sample two values.
I've used this flow and when I press both injects, the MathUltimate block writes "Waiting for msg.topic"

`[{"id":"430cc033ed140940","type":"inject","z":"d35c1a8f1f3d7120","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Cost per KWh","payload":"20","payloadType":"num","x":240,"y":680,"wires":[["97d95d92ddf4bf08"]]},{"id":"1793931ba218bc1d","type":"inject","z":"d35c1a8f1f3d7120","name":"Reset","props":[{"p":"reset","v":"","vt":"date"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":210,"y":740,"wires":[["05b6ce0cb476abd5","97d95d92ddf4bf08","0e336df4446a1c5d"]]},{"id":"514067713f250a42","type":"inject","z":"d35c1a8f1f3d7120","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"Wh Washing machine","payload":"2001","payloadType":"num","x":240,"y":620,"wires":[["97d95d92ddf4bf08"]]},{"id":"97d95d92ddf4bf08","type":"SumUltimate","z":"d35c1a8f1f3d7120","name":"Multiply","property":"payload","math":"subtract","subtractstartfrom":"msg.topic","x":440,"y":680,"wires":[["d4e0ea654df96bab"]]},{"id":"d4e0ea654df96bab","type":"debug","z":"d35c1a8f1f3d7120","name":"Result","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":670,"y":680,"wires":[]}]`

![2024-05-05 10_59_56-Node-RED – Home Assistant](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/28533921/6db07d22-142b-4a12-ac39-bbb142e24a31)

**Comment by Supergiovane** [comment]
Hi
You must set two different topics for the incoming messages.

**Comment by Sectorchan** [comment]
When I change one the msg.topic to msg.topic2 and the other is still msg.topic
![chnangetopic](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/28533921/ef1893f3-a91d-4ca5-8175-4324a50bc1a6)
I receive incomming msg without topic

`[{"id":"430cc033ed140940","type":"inject","z":"d35c1a8f1f3d7120","name":"","props":[{"p":"payload"},{"p":"topic2","v":"10","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":210,"y":680,"wires":[["97d95d92ddf4bf08"]]},{"id":"514067713f250a42","type":"inject","z":"d35c1a8f1f3d7120","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"21","payload":"2001","payloadType":"num","x":180,"y":620,"wires":[["97d95d92ddf4bf08"]]},{"id":"97d95d92ddf4bf08","type":"SumUltimate","z":"d35c1a8f1f3d7120","name":"Multiply","property":"payload","math":"subtract","subtractstartfrom":"msg.topic","x":440,"y":680,"wires":[["d4e0ea654df96bab"]]}]`

**Comment by Supergiovane** [comment]
Hi
sorry the late response.
Please take a look here. I modified your nodes:

```javascript

[
    {
        "id": "430cc033ed140940",
        "type": "inject",
        "z": "1050ddfb1ce105e8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "10",
        "payload": "20",
        "payloadType": "num",
        "x": 110,
        "y": 160,
        "wires": [
            [
                "97d95d92ddf4bf08"
            ]
        ]
    },
    {
        "id": "514067713f250a42",
        "type": "inject",
        "z": "1050ddfb1ce105e8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "start",
        "payload": "2001",
        "payloadType": "num",
        "x": 120,
        "y": 100,
        "wires": [
            [
                "97d95d92ddf4bf08"
            ]
        ]
    },
    {
        "id": "97d95d92ddf4bf08",
        "type": "SumUltimate",
        "z": "1050ddfb1ce105e8",
        "name": "Subtraco",
        "property": "payload",
        "math": "subtract",
        "subtractstartfrom": "start",
        "x": 380,
        "y": 160,
        "wires": [
            [
                "c55f332fe2dadc53"
            ]
        ]
    },
    {
        "id": "c55f332fe2dadc53",
        "type": "debug",
        "z": "1050ddfb1ce105e8",
        "name": "debug 6",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 380,
        "y": 320,
        "wires": []
    }
]
```

**Comment by Sectorchan** [comment]
Awesome! Thank you very much! 
Now I've understood it
I hope Im not the only one who didn't understood it :x

**Comment by Supergiovane** [comment]
You're not the only one.
I've changed the help text, to better explain the use of such msg.topic.
Sorry for that!

**Comment by Sectorchan** [comment]
No problem! you helped me alot with your response and information!
