### ISSUE TITLE
New version 1.1.10 Install / Update issue 

### ISSUE THREAD

**Issue by santi-wg** [Supergiovane/node-red-contrib-boolean-logic-ultimate#46]
Update 1.1.9 to 1.1.10 or new install 1.1.10 issue
node js version :  20.14.0 (updated to last version nodejs)
npm version : 10.7.0 (updated to last version npm)
nodered version : 3.1.9 (updated to last version nodered)
![Screenshot_2024-06-04_16-32-39](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/88175726/5df32cac-2008-499c-8016-0646153639a8)
this picture version 1.1.9 no problem

![Screenshot_2024-06-04_16-33-56](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/88175726/2529c362-9b5c-4b78-a7ee-06b31d8ab85b)
this picture version  1.1.10 has problem (MODULE_NOT_FOUND)

I have tried many ways to solve the problem but it didn't work.
1. npm Install old version 1.1.9 and update to 1.1.10 --> not work
2. Remove 1.1.10 and new install --> not work
3. Remove "All" palette and install only this (boolean-logic-ultimate 1.1.10) --> not work
4. Delete folder "node_modules" , delete file "package.json" and install only this -- > not work
5. npm install old version (1.1.9) no problem

Sorry for my english
Thank you

**Comment by Supergiovane** [comment]
Hi
that's very strange.
If you pass the mouse on the yellow triangle, does it tells you the missing module's name? 
Or maybe you can search the node-red log for the error.
In the meantime, i'm looking into the code...

**Comment by santi-wg** [comment]
syslog Node-RED
[warn] [node-red-contrib-boolean-logic-ultimate/InjectUltimate] Error: Cannot find module '@project-chip/matter-node.js/common'

**Comment by Supergiovane** [comment]
Nevermind.
Found the issue.
Please update to 1.1.11

**Comment by santi-wg** [comment]
Thank you
1.1.11 solve this issue
![Screenshot_2024-06-04_17-18-27](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/88175726/ea25e93e-f233-4baf-8f4c-a7c73ccd6cb0)
