### ISSUE TITLE
Feature Request: Multiple Railway Inputs

### ISSUE THREAD

**Issue by Hypoferalcus** [Supergiovane/node-red-contrib-boolean-logic-ultimate#47]
Hi there!

I hope, this is the right place to post that - I really love the Plugin, especially the railway inputs. And I really appreciate the increase to 5 outputs.
What would be a really cool addition would be to also increase the number of inputs - So we could have some more complex flows with the railway node as the central point.

thanks in advance

**Comment by Supergiovane** [comment]
Hi
It's not possible in Node-Red to add more than 1 input PIN.
Can you describe, what you're trying to achieve? I'll get a shot then.
Thanks.

**Comment by Hypoferalcus** [comment]
Wow thanks for the super-fast answer!
The problem to solve is - for example - a lighting scene (with KNX Node as receipient) which should be different when we have "guest-mode", "holiday-mode" or "standard-mode" - right now I am using multiple Railway inputs with one output connected to the KNX node and the other one (while it was only 2 outputs) just empty, so the payloads just end in "nowhere".
That works, but of course it would have been more elegant to have just one railway node with multi-inputs.

**Comment by Supergiovane** [comment]
Hi
Ok, understood.
You can do that with the payload.
See the help panel, and see if it fits your needs. If not, please paste your flow here, i'll give it a shot. :-)

<img width="574" alt="Node-RED___Avvio" src="https://github.com/user-attachments/assets/bf0ef1fc-7c3e-4ce7-af9a-4eec266f330d">
