### ISSUE TITLE
Railway node changes payload from boolean to string

### ISSUE THREAD

**Issue by Hypoferalcus** [Supergiovane/node-red-contrib-boolean-logic-ultimate#48]
Hi there!

The new railway node seems to change a boolean true/false input to a string 1/0 output.
I tried a new inject node with boolen true/false directly to a debug node and it went fine.
Once i put a railway node between those, it changes the output to 1/0 as string.
Although some nodes do handle 1 and 0 equal to true and false, some do not (e.g. "switch" oder "change" nodes).
Is that maybe a bug?

Kind regards

**Comment by Supergiovane** [comment]
Hi
Hmmm… that’s very strange. 
Tomorrow i’ll take a look.

**Comment by Supergiovane** [comment]
Fixed in 3.1.7, out now.
Thank you for pointing me out that.

**Comment by Hypoferalcus** [comment]
Thank you - works fine after the update!
