### ISSUE TITLE
Impulse node issue

### ISSUE THREAD

**Issue by hawkeye1103** [Supergiovane/node-red-contrib-boolean-logic-ultimate#49]
Hello it seems i've stumbled upon a issue with the impulse node. It seems every time i turn it off it turns on on it's own. Is this a feature or a bug?:)
added the configuration of my node and a video of the issue
node config: 

send:true
wait:300000
send:true
wait:300000
restart

https://youtu.be/b1_Uf80Qhr0

Thanks in advance

**Comment by Supergiovane** [comment]
Hi
I think it’s a bug. I’ll take a look..

**Comment by Supergiovane** [comment]
Hi
i cannot reproduce the issue.
Mine is working fine. Can you paste here your flow, so i can check it?
Are you on the latest boolean-logic-ultimate version?
https://github.com/user-attachments/assets/af431ffc-ddb4-4b0e-aa4b-ccf2cde2af64

**Comment by hawkeye1103** [comment]
Hello,

`[{"id":"5aa5e0c52cdb50c4","type":"tab","label":"Bedroom Thermostat","disabled":false,"info":"","env":[]},{"id":"574c0f1db973ca84","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom AC","server":"cedf8a15.edfa18","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"climate.bedroom_ac","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":870,"y":60,"wires":[["ef4c7a38aa0d1bf9"]]},{"id":"524a09d197a62a0d","type":"ha-switch","z":"5aa5e0c52cdb50c4","name":"switch_automation","version":0,"debugenabled":false,"inputs":1,"outputs":2,"entityConfig":"46f40c97e5a9cccc","enableInput":true,"outputOnStateChange":true,"outputProperties":[{"property":"outputType","propertyType":"msg","value":"change state","valueType":"str"},{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"}],"x":110,"y":20,"wires":[["7c8e4d2203494515"],["7c8e4d2203494515"]]},{"id":"ef4c7a38aa0d1bf9","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"cool","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1050,"y":60,"wires":[["f212d553611e6677"],["f212d553611e6677"]]},{"id":"15f75f61b7e8e2a0","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Temperature sensor","server":"b904d13b.0c72","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"sensor.a4c13860c7c7_temperature","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"},{"property":"topic","propertyType":"msg","value":"temp_sensor","valueType":"str"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":224,"y":282,"wires":[["a8e75b6bab0b4854"]]},{"id":"bab022f429bc3e92","type":"ha-number","z":"5aa5e0c52cdb50c4","name":"set_temperature_bedroom","version":1,"debugenabled":false,"inputs":0,"outputs":1,"entityConfig":"b9cdfb9559e8069a","mode":"listen","value":"payload","valueType":"msg","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"num"},{"property":"previousValue","propertyType":"msg","value":"","valueType":"previousValue"},{"property":"topic","propertyType":"msg","value":"temp_value","valueType":"str"}],"x":150,"y":420,"wires":[["49678fa2d58fb557"]]},{"id":"49678fa2d58fb557","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Set Temperature","server":"b904d13b.0c72","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"number.set_temp_bedroom","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"},{"property":"topic","propertyType":"msg","value":"temp_value","valueType":"str"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":204,"y":342,"wires":[["a8e75b6bab0b4854","f5757b0be8f2264c"]]},{"id":"7ed57c13be645628","type":"poll-state","z":"5aa5e0c52cdb50c4","name":"","server":"b904d13b.0c72","version":3,"exposeAsEntityConfig":"","updateInterval":"60","updateIntervalType":"num","updateIntervalUnits":"seconds","outputInitially":false,"outputOnChanged":false,"entityId":"switch.nodered_46f40c97e5a9cccc","stateType":"str","ifState":"true","ifStateType":"str","ifStateOperator":"is","outputs":2,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":350,"y":960,"wires":[[],[]]},{"id":"a8e75b6bab0b4854","type":"SumUltimate","z":"5aa5e0c52cdb50c4","name":"Math","property":"payload","math":"subtract","subtractstartfrom":"temp_sensor","x":414,"y":322,"wires":[["7a013d62944a2c8c"]]},{"id":"3c9877bbdbd2f3c6","type":"ImpulseUltimate","z":"5aa5e0c52cdb50c4","name":"Message every 5m","commandText":"// Open garage door\nsend:true\nwait:300000\nsend:true\nwait:300000\nrestart","payloadPropName":"payload","x":370,"y":60,"wires":[["b6ff8b06703b5388"]]},{"id":"b6ff8b06703b5388","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom Window","server":"cedf8a15.edfa18","version":3,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"binary_sensor.0x00158d0008064347_contact","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":610,"y":60,"wires":[["a85948492a9090bb"],["574c0f1db973ca84"]]},{"id":"234e136e769c3e8b","type":"change","z":"5aa5e0c52cdb50c4","name":"Set message to false","rules":[{"t":"change","p":"payload","pt":"msg","from":"on","fromt":"str","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":840,"y":140,"wires":[["9ae0e998774cad45"]]},{"id":"a85948492a9090bb","type":"delay","z":"5aa5e0c52cdb50c4","name":"","pauseType":"rate","timeout":"4.5","timeoutUnits":"minutes","rate":"1","nbRateUnits":"11","rateUnits":"minute","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":160,"y":140,"wires":[["defa6d20a7986e22"]]},{"id":"596bcdbc3f1648df","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom Window","server":"cedf8a15.edfa18","version":3,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"binary_sensor.0x00158d0008064347_contact","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":590,"y":140,"wires":[["234e136e769c3e8b"],[]]},{"id":"a50fac6776bb65bc","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn ON Bedroom AC","server":"cedf8a15.edfa18","version":5,"debugenabled":true,"domain":"climate","service":"turn_on","areaId":[],"deviceId":["024dbc1a884ab0b2955b18339ff064d9"],"entityId":["climate.bedroom_ac"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1300,"y":280,"wires":[[]]},{"id":"f212d553611e6677","type":"link out","z":"5aa5e0c52cdb50c4","name":"link out 1","mode":"link","links":["7fbed8b040fe76d0"],"x":1155,"y":60,"wires":[]},{"id":"7fbed8b040fe76d0","type":"link in","z":"5aa5e0c52cdb50c4","name":"link in 1","links":["f212d553611e6677"],"x":77,"y":314,"wires":[["15f75f61b7e8e2a0","49678fa2d58fb557"]]},{"id":"9d4469f537e555f0","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn OFF Bedroom AC","server":"cedf8a15.edfa18","version":5,"debugenabled":true,"domain":"climate","service":"turn_off","areaId":[],"deviceId":["024dbc1a884ab0b2955b18339ff064d9"],"entityId":["climate.bedroom_ac"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1300,"y":340,"wires":[[]]},{"id":"2b59e1bb75ab908c","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":750,"y":320,"wires":[["de70ecbe7993d461"],["64132a960a54e178"]]},{"id":"793a87b75ef48e99","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Set Bedroom AC Temperature","server":"cedf8a15.edfa18","version":5,"debugenabled":true,"domain":"climate","service":"set_temperature","areaId":[],"deviceId":["024dbc1a884ab0b2955b18339ff064d9"],"entityId":["climate.bedroom_ac"],"data":"{\"temperature\": payload}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":850,"y":400,"wires":[[]]},{"id":"de70ecbe7993d461","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom AC","server":"cedf8a15.edfa18","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"climate.bedroom_ac","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":930,"y":280,"wires":[["380de85e10589ce6"]]},{"id":"64132a960a54e178","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom AC","server":"cedf8a15.edfa18","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"climate.bedroom_ac","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":930,"y":340,"wires":[["136becf4c3b34c4f"]]},{"id":"136becf4c3b34c4f","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"cool","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1110,"y":340,"wires":[["9d4469f537e555f0"],[]]},{"id":"380de85e10589ce6","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"cool","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":1110,"y":280,"wires":[[],["a50fac6776bb65bc"]]},{"id":"ecd3f33ec3b9e73e","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Bedroom Speaker Message","server":"cedf8a15.edfa18","version":5,"debugenabled":false,"domain":"tts","service":"google_say","areaId":[],"deviceId":[],"entityId":["media_player.googlehome8665"],"data":"{\"message\":\"Bedroom window is open, AC will turn off in 10 minutes\"}","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":717.9999847412109,"y":585.9999904632568,"wires":[[]]},{"id":"d659af4f2d3ea386","type":"delay","z":"5aa5e0c52cdb50c4","name":"","pauseType":"delay","timeout":"10","timeoutUnits":"minutes","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":670.0000114440918,"y":534.000007390976,"wires":[["a2fa9b3c9c0355b3"]]},{"id":"2bb81683f724a26b","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom AC","server":"cedf8a15.edfa18","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"climate.bedroom_ac","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":310,"y":540,"wires":[["64f49c13d333f9aa"]]},{"id":"a2fa9b3c9c0355b3","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom Window","server":"cedf8a15.edfa18","version":3,"outputs":2,"halt_if":"on","halt_if_type":"str","halt_if_compare":"is","entity_id":"binary_sensor.0x00158d0008064347_contact","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":880.0000152587891,"y":534.0000095367432,"wires":[["f6a280030841d9d7"],[]]},{"id":"f6a280030841d9d7","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn OFF Bedroom AC","server":"cedf8a15.edfa18","version":5,"debugenabled":true,"domain":"climate","service":"turn_off","areaId":[],"deviceId":["024dbc1a884ab0b2955b18339ff064d9"],"entityId":["climate.bedroom_ac"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1120,"y":527,"wires":[[]]},{"id":"64f49c13d333f9aa","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"cool","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":490,"y":540,"wires":[["ecd3f33ec3b9e73e","d659af4f2d3ea386"],[]]},{"id":"76cd1fa692c0d89a","type":"ha-device","z":"5aa5e0c52cdb50c4","name":"Bedroom Window","server":"cedf8a15.edfa18","version":1,"exposeAsEntityConfig":"707d76afcb5fb5b2","inputs":0,"deviceType":"trigger","device":"76fa0bea257b296ea66ac3613b72f69c","event":{"type":"opened","platform":"device","device_id":"76fa0bea257b296ea66ac3613b72f69c","entity_id":"binary_sensor.0x00158d0008064347_contact","domain":"binary_sensor","metadata":{"secondary":false}},"capabilities":[],"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"date"},{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"}],"x":110,"y":540,"wires":[["2bb81683f724a26b"]]},{"id":"3bde2635b911ad1a","type":"inject","z":"5aa5e0c52cdb50c4","name":"Turn off 5AM","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"00 05 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":660,"wires":[["0f32c620b7900cdd"]]},{"id":"f281ec6577f8187c","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"Check Bedroom AC","server":"cedf8a15.edfa18","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"climate.bedroom_ac","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":682.0000152587891,"y":653.0000104904175,"wires":[["ad3249ece5f4262e"]]},{"id":"0f32c620b7900cdd","type":"api-current-state","z":"5aa5e0c52cdb50c4","name":"","server":"b904d13b.0c72","version":3,"outputs":2,"halt_if":"home","halt_if_type":"str","halt_if_compare":"is","entity_id":"device_tracker.sm_s928b","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"for":"0","forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":400,"y":660,"wires":[["f281ec6577f8187c"],[]]},{"id":"ad3249ece5f4262e","type":"switch","z":"5aa5e0c52cdb50c4","name":"","property":"payload","propertyType":"msg","rules":[{"t":"neq","v":"off","vt":"str"},{"t":"eq","v":"off","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":855.0000152587891,"y":653.0000104904175,"wires":[["5d4def4250c369fe","41916db8b3492ef1"],[]]},{"id":"5d4def4250c369fe","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn OFF Bedroom AC","server":"cedf8a15.edfa18","version":5,"debugenabled":true,"domain":"climate","service":"turn_off","areaId":[],"deviceId":["024dbc1a884ab0b2955b18339ff064d9"],"entityId":["climate.bedroom_ac"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1037.000015258789,"y":646.0000104904175,"wires":[[]]},{"id":"9ae0e998774cad45","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn off automation","server":"b904d13b.0c72","version":5,"debugenabled":false,"domain":"switch","service":"turn_off","areaId":[],"deviceId":[],"entityId":["switch.nodered_46f40c97e5a9cccc"],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1070,"y":140,"wires":[[]]},{"id":"defa6d20a7986e22","type":"delay","z":"5aa5e0c52cdb50c4","name":"","pauseType":"delay","timeout":"10","timeoutUnits":"minutes","rate":"1","nbRateUnits":"10","rateUnits":"minute","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":true,"allowrate":false,"outputs":1,"x":350,"y":140,"wires":[["596bcdbc3f1648df"]]},{"id":"6c9949e53c41ef52","type":"function","z":"5aa5e0c52cdb50c4","name":"Round up temperature","func":"msg.payload -= 1;\nvar round = Math.round(msg.payload)\nround = msg.payload;\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":580,"y":380,"wires":[["793a87b75ef48e99"]]},{"id":"7a013d62944a2c8c","type":"function","z":"5aa5e0c52cdb50c4","name":"Trigger <=0 >=2","func":"var temp_delta = msg.payload\n\nif ( temp_delta <= 10) {\n\n    if ( temp_delta <= 0) {\n        msg.payload = false\n    }\n\n    else if ( temp_delta >= 1.5 ) {\n        msg.payload = true\n    }\n    else {\n    msg.payload = null\n}\n\n}\n\nelse {\n    msg.payload = null\n}\n\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":584,"y":322,"wires":[["2b59e1bb75ab908c"]]},{"id":"f5757b0be8f2264c","type":"rbe","z":"5aa5e0c52cdb50c4","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":true,"property":"payload","topi":"topic","x":410,"y":380,"wires":[["6c9949e53c41ef52"]]},{"id":"3084b83d07ef8c9a","type":"inject","z":"5aa5e0c52cdb50c4","name":"Send 27c at 23:00","props":[{"p":"payload"}],"repeat":"","crontab":"00 23 * * *","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":480,"wires":[["19bc107d4ac2dcc7"]]},{"id":"19bc107d4ac2dcc7","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"set_temp_bedroom modify","server":"b904d13b.0c72","version":5,"debugenabled":false,"domain":"number","service":"set_value","areaId":[],"deviceId":[],"entityId":["number.set_temp_bedroom"],"data":"{\"value\":27}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":380,"y":480,"wires":[[]]},{"id":"41916db8b3492ef1","type":"api-call-service","z":"5aa5e0c52cdb50c4","name":"Turn off automation","server":"b904d13b.0c72","version":5,"debugenabled":false,"domain":"switch","service":"turn_off","areaId":[],"deviceId":[],"entityId":["switch.nodered_46f40c97e5a9cccc"],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":1050,"y":700,"wires":[[]]},{"id":"bbf69d50b93e25b7","type":"inject","z":"5aa5e0c52cdb50c4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":150,"y":80,"wires":[["3c9877bbdbd2f3c6"]]},{"id":"7c8e4d2203494515","type":"debug","z":"5aa5e0c52cdb50c4","name":"debug 4","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":340,"y":20,"wires":[]},{"id":"3802630bc1a4ce8b","type":"function","z":"5aa5e0c52cdb50c4","name":"function 1","func":"\nreturn msg;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":200,"y":220,"wires":[[]]},{"id":"cedf8a15.edfa18","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true},{"id":"46f40c97e5a9cccc","type":"ha-entity-config","server":"cedf8a15.edfa18","deviceConfig":"","name":"exposed as for 46f40c97e5a9cccc","version":6,"entityType":"switch","haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"resend":false},{"id":"b904d13b.0c72","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true},{"id":"b9cdfb9559e8069a","type":"ha-entity-config","server":"b904d13b.0c72","deviceConfig":"","name":"","version":"6","entityType":"number","haConfig":[{"property":"name","value":"Set Temp Bedroom"},{"property":"icon","value":""},{"property":"entity_picture","value":""},{"property":"entity_category","value":"config"},{"property":"device_class","value":"temperature"},{"property":"unit_of_measurement","value":"°C"},{"property":"min_value","value":8},{"property":"max_value","value":30},{"property":"step_value","value":0.5},{"property":"mode","value":"slider"}],"resend":false,"debugEnabled":false},{"id":"707d76afcb5fb5b2","type":"ha-entity-config","server":"cedf8a15.edfa18","deviceConfig":"","name":"exposed as for Bedroom Window","version":6,"entityType":"switch","haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"resend":false}]`

This is the flow and i am on version 1.1.17

Thanks

**Comment by Supergiovane** [comment]
Hi
how are you starting the node? (you should start it with msg.payload=true, but i don't see any inject node doing this).

**Comment by hawkeye1103** [comment]
Hi,

The switch node above that is called "switch_automation" is doing that. I changed it like this for some testing purposes. and it's sending true and false.

![image](https://github.com/user-attachments/assets/652e7933-a72f-4fb2-9108-adb488d437fd)


Also i've recreated the impulse node and it's not doing that anymore (deleted the old one and copied the code to a new one pulled from the left menu bar).

**Comment by Supergiovane** [comment]
No, mine is working fine. I suspect a glitch in the sample code (maybe a malformed char).
Anyway, i've made a little change in the sop procedure.
As soon as you see the new version 1.1.18, install it and try.

**Comment by Supergiovane** [comment]
1.1.18 is published, you should see it in some minutes.
Are you sure the "HA switch" node before the impulse ultimate node, is sending out a msg.payload = true and msg.payload = false?

**Comment by hawkeye1103** [comment]
> No, mine is working fine. I suspect a glitch in the sample code (maybe a malformed char). Anyway, i've made a little change in the sop procedure. As soon as you see the new version 1.1.18, install it and try.

Thanks i'll give it a go and report back. 
Yes yes positive it's sending true and false.
![image](https://github.com/user-attachments/assets/649ad5e5-72a2-4f57-8af7-5216828e19b5)

**Comment by hawkeye1103** [comment]
Hey sorry for the delay. It's not, in the video i've sent you (in the first post) it was an inject node that was sending the false.

**Comment by Supergiovane** [comment]
Hi
Is this problem solved?
