### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by da110us** [Supergiovane/node-red-contrib-boolean-logic-ultimate#5]
trying to install this node on Home Assistant / Node Red combination. When I try to install in the palet it claims it needs dependencies. I can't find any dependencies. 

I'm quite new to Node Red, so perhaps I'm missing out on something. Could you give me some directions how to install the dependencies?

**Comment by Supergiovane** [comment]
Leave me check...

**Comment by Supergiovane** [comment]
There is no issues with dependency in the node itself.
Wich dependency is missing? Can you read it in the palette's log?

**Comment by da110us** [comment]
[cid:image004.jpg@01D62478.7A2B93C0]

[cid:image005.jpg@01D62478.7A2B93C0]

[cid:image006.jpg@01D62478.7A2B93C0]



Met vriendelijke groet,

Martijn de Haas

Van: Supergiovane <notifications@github.com>
Verzonden: donderdag 7 mei 2020 13:33
Aan: Supergiovane/node-red-contrib-boolean-logic-ultimate <node-red-contrib-boolean-logic-ultimate@noreply.github.com>
CC: Martijn de Haas <martijn@coreiq.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Supergiovane/node-red-contrib-boolean-logic-ultimate] Dependencies (#5)


There is no issues with dependency in the node itself.
Wich dependency is missing? Can you read it in the palette's log?

**Comment by da110us** [comment]
-----------------------------------------------------------
2020-05-07T11:03:18.133Z Install : node-red-contrib-boolean-logic-ultimate 1.0.14

2020-05-07T11:03:17.953Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-boolean-logic-ultimate@1.0.14

-----------------------------------------------------------
2020-05-07T12:03:49.340Z Install : node-red-contrib-boolean-logic-ultimate 1.0.14

2020-05-07T12:03:49.364Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-boolean-logic-ultimate@1.0.14

**Comment by Supergiovane** [comment]
There's no errors here. Have you tried to reboot your system and repeat the installation?

**Comment by da110us** [comment]
That seems to do the trick! Install finished, now rebooting to complete.

Thanks for the quick response!!



Met vriendelijke groet,

Martijn de Haas

Core IQ<file://iq>
t: +31-6-28824142
e: martijn@coreiq.nl<mailto:martijn@coreiq.nl>


Core IQ / Lisse
KvK Den Haag 54469929

Van: Supergiovane <notifications@github.com>
Verzonden: donderdag 7 mei 2020 14:15
Aan: Supergiovane/node-red-contrib-boolean-logic-ultimate <node-red-contrib-boolean-logic-ultimate@noreply.github.com>
CC: Martijn de Haas <martijn@coreiq.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [Supergiovane/node-red-contrib-boolean-logic-ultimate] Dependencies (#5)


There's no errors here. Have you tried to reboot your system and repeat the installation?
