### ISSUE TITLE
Node Math

### ISSUE THREAD

**Issue by jo-mat** [Supergiovane/node-red-contrib-boolean-logic-ultimate#50]
Hi
A lite bug:
When I make a multiplication by 0 the node don't give 0 ...
Ex : 20*0 = 20

Thks for your job
José

**Comment by Supergiovane** [comment]
node-red-contrib-boolean-logic-ultimate@1.1.23 has been released, with the fix.

**Comment by jo-mat** [comment]
Grazie mille
