### ISSUE TITLE
Persistence not working after node-red restart 

### ISSUE THREAD

**Issue by Botched1** [Supergiovane/node-red-contrib-boolean-logic-ultimate#7]
Not sure if this is new to Node-RED 1.2.x, is because I run node-red in a docker container, or other, but...

After a node-red restart I am losing all persistent states and the boolean node is starting as uninitialized. I verified that the "remember" checkbox IS checked.

EDIT: I rolled the container back to 1.1.3 and get the same thing, so I guess it is not a NR 1.2.x issue. Must be something with my container install I guess. 🤷‍♂️

**Comment by Supergiovane** [comment]
Hi
Please be sure that the node-red’s user, has the rights to write to the filesystem. 
For example, is node red is running under other user than root, simoly give this user the rights to write to the filesystem
😉

**Comment by Botched1** [comment]
If I'm the only one complaining, I'm sure the issue is on my end. That said, I've tried running the container as multiple different users (root, node-red:dialout, etc), and get the same thing each time. 

After I reboot I just see this on the node:
![image](https://user-images.githubusercontent.com/19985320/97094812-0560ec00-161e-11eb-826f-b1b29216ae43.png)

**Comment by Botched1** [comment]
EDIT: Never mind, it is definitely a docker/permissions issue. Instead of running it in Portainer, I made the container from scratch with "-u node-red:dialout" and persistence works as expected.

I'll close this.
