### ISSUE TITLE
Persistence when using in Docker container

### ISSUE THREAD

**Issue by Botched1** [Supergiovane/node-red-contrib-boolean-logic-ultimate#8]
As a follow up to my issue report from yesterday...

The issue I am seeing is not a permissions problem. The "issue" (if you want to call it that) is that the states directory is saved in the running users folder instead of the node-red --userDir.

When running in docker, the only folder that typically has persistence is the specified --userDir directory (which is /data).

If I could make a suggestion/feature request, I would love to see you store your states directory in the node-red userDir directory, and not in the default user home or working directory. I believe this indirectly resolves many permission issues, too, as I **think** the running user always has to have edit capability in the user directory for node-red to work/run.

Something a la: 
const statesDir = path.join(RED.settings.userDir, "states")

**Comment by Supergiovane** [comment]
Hi Botched
Thak you for your suggestion. 
Yes, i’lll change that in the next release!

**Comment by Supergiovane** [comment]
Hi Botched
V. 1.0.21 is out with this fix. Cheers and thanks.

**Comment by Botched1** [comment]
> Hi Botched
> V. 1.0.21 is out with this fix. Cheers and thanks.

Just tested 1.0.22, and can confirm that persistence works as expected in a docker install (as long as the /data directory has persistence, of course).

Nice job, and thanks!
