### ISSUE TITLE
Boolean logic doesn't reset itself

### ISSUE THREAD

**Issue by KarstenSiemer** [Supergiovane/node-red-contrib-boolean-logic-ultimate#9]
Hi!
First of all thanks for this amazing work and sorry if I am just misunderstanding something, but
by boolean logic node never resets itself after it received the amount of topics it was waiting for.

I have this set up for example:
![image](https://user-images.githubusercontent.com/40307978/102635382-85ee2580-4153-11eb-8e2c-0e0ca84e525b.png)
![image](https://user-images.githubusercontent.com/40307978/102635455-a1f1c700-4153-11eb-9b69-fb916fa4942e.png)

it works the first time perfectly! It waits until all 3 topics arrived and then merges them and outputs one single boolean out of all 3 nodes.

But after this, it outputs whenever a single inject node sends something, so if all 3 nodes send again, the boolean logic node outputs 3 booleans instead of just one.

I want it to start fresh each time it received all 3 topics which is also the expected behavior in my opinion from reading the documentation:
>If it ever sees more than the configured number of topics it will log a message then reset its state and start over.

What am I doing wrong here?
Thanks in advance for the help!

**Comment by KarstenSiemer** [comment]
I see. If I add another inject node with a fourth topic and send this, then the boolean logic node resets itself.
Is there a way to have this done without the fourth inject node? Like I have described in my last comment?

**Comment by KarstenSiemer** [comment]
Ok, I added a delay node to a switch with a 2 second delay. This wipes the state of the logic node.
If one of the requests fails, this resets the node. Is this why an additional topic is needed?
![image](https://user-images.githubusercontent.com/40307978/102637289-0e6dc580-4156-11eb-81b6-3ff8b74c6609.png)

**Comment by Supergiovane** [comment]
Hi Karsten
Yes, the default boolean logic node of node-red works exaclty the same way. For logic to be evaluated, the node, in your case, needs to receive messages from 3 different topics.

**Comment by KarstenSiemer** [comment]
Like never use it they way I did or do you mean like node-red does on default?
Is there a way to reset without a fourth node?

**Comment by Supergiovane** [comment]
You should never need to reset a boolean logic, otherwise it’s not a boolean logic anymore. 
What do you want to achieve?

**Comment by KarstenSiemer** [comment]
There is probably a smarter way to do this.
I have smart thermostats for my heaters at home and quite big rooms.
As soon as I open a single window, I want to shut down the thermostat to not loose any unnecessary heat.
I do track the statuses of all windows. Open is "true" and shut is "false".

When a window changes its status I want to check if either at least one window is open or none.
The first trigger will work perfectly since all window positions get checked and "OR" merged in the boolean logic node.
All windows shut = false = thermostat is allowed to heat the room.
At least one windows open = true = thermostat off

If a window status change changes the logic node to true on a topic the output of the node is correct but in my case get output 3 times.

By writing down what happens, I start to get why resetting is actually unnecessary. The node tracks all topics and will always output the correct boolean.
I just need to stop asking all window positions and directly input the nodes. Since the boolean node tracks the topics, I do not need to check all windows each time.

Thanks for the help!

**Comment by Supergiovane** [comment]
Yes. You can put another rbe node after the boolean logic, so you’ll have not 3, but only 1 message.

**Comment by KarstenSiemer** [comment]
Also smart. I am not used to low code solutions like node-red. Thanks for helping me learn 👍
